/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza.project;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sambhavshrestha
 */

public class PizzaShopApplication extends javax.swing.JFrame {

    /**
     * Creates new form PizzaShopApplication
     */
    public PizzaShopApplication() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Checkout = new javax.swing.JLabel();
        cancelbutton = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        orderbutton = new javax.swing.JButton();
        totalBox = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        tipBox = new javax.swing.JFormattedTextField();
        tipCombobox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        toppingPanel = new javax.swing.JPanel();
        Toppings = new javax.swing.JLabel();
        checkPepperoni = new javax.swing.JCheckBox();
        checkPineappple = new javax.swing.JCheckBox();
        checkMushroom = new javax.swing.JCheckBox();
        checkMeatball = new javax.swing.JCheckBox();
        checkChicken = new javax.swing.JCheckBox();
        checkOnions = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        Crust = new javax.swing.JLabel();
        radioThin = new javax.swing.JRadioButton();
        radioThick = new javax.swing.JRadioButton();
        radioCheese = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        Styles = new javax.swing.JLabel();
        radioNewYork = new javax.swing.JRadioButton();
        radioChicago = new javax.swing.JRadioButton();
        radioSicilian = new javax.swing.JRadioButton();
        radioVeggie = new javax.swing.JRadioButton();
        radioEverything = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(23, 28, 38));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        Checkout.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        Checkout.setForeground(new java.awt.Color(255, 255, 255));
        Checkout.setText("Checkout");

        cancelbutton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("Total");

        orderbutton.setBackground(new java.awt.Color(153, 255, 153));
        orderbutton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        orderbutton.setText("Place Order");
        orderbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbuttonActionPerformed(evt);
            }
        });

        totalBox.setEditable(false);
        totalBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        totalBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        totalBox.setValue(0.00);
        totalBox.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                totalBoxInputMethodTextChanged(evt);
            }
        });
        totalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBoxActionPerformed(evt);
            }
        });
        totalBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalBoxPropertyChange(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Quantity");

        tip.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        tip.setText("Tip");

        quantitySpinner.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        quantitySpinner.setMixingCutoutShape(null);
        quantitySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantitySpinnerStateChanged(evt);
            }
        });

        tipBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tipBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tipBox.setValue((double)0);
        tipBox.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tipBoxInputMethodTextChanged(evt);
            }
        });
        tipBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipBoxActionPerformed(evt);
            }
        });

        tipCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "15%", "20%", "30%", "40%" }));
        tipCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipComboboxActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tipCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(orderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Checkout)
                        .addGap(127, 127, 127))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(cancelbutton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(orderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        toppingPanel.setBackground(new java.awt.Color(255, 255, 204));
        toppingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Toppings.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        Toppings.setText("Select Toppings:");

        checkPepperoni.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkPepperoni.setText("Pepperoni   (+$2.00)");
        checkPepperoni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPepperoniItemStateChanged(evt);
            }
        });
        checkPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPepperoniActionPerformed(evt);
            }
        });

        checkPineappple.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkPineappple.setText("Pineapple   (+$2.40)");
        checkPineappple.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPineapppleItemStateChanged(evt);
            }
        });
        checkPineappple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPineapppleActionPerformed(evt);
            }
        });

        checkMushroom.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkMushroom.setText("Mushroom (+$3.40)");
        checkMushroom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkMushroomItemStateChanged(evt);
            }
        });
        checkMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMushroomActionPerformed(evt);
            }
        });

        checkMeatball.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkMeatball.setText("Meatball    (+$2.10)");
        checkMeatball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkMeatballItemStateChanged(evt);
            }
        });
        checkMeatball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMeatballActionPerformed(evt);
            }
        });

        checkChicken.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkChicken.setText("Chicken     (+$3.25)");
        checkChicken.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkChickenItemStateChanged(evt);
            }
        });

        checkOnions.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        checkOnions.setText("Onions, Peppers (+$1.80)");
        checkOnions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkOnionsItemStateChanged(evt);
            }
        });
        checkOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOnionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppingPanelLayout = new javax.swing.GroupLayout(toppingPanel);
        toppingPanel.setLayout(toppingPanelLayout);
        toppingPanelLayout.setHorizontalGroup(
            toppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingPanelLayout.createSequentialGroup()
                .addGroup(toppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toppingPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Toppings))
                    .addGroup(toppingPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(toppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPepperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(toppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkPineappple, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkMeatball, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppingPanelLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(checkOnions)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        toppingPanelLayout.setVerticalGroup(
            toppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Toppings)
                .addGap(26, 26, 26)
                .addComponent(checkPepperoni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPineappple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkMushroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkMeatball, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkChicken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOnions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Crust.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        Crust.setText("Select Crust:");

        buttonGroup1.add(radioThin);
        radioThin.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioThin.setText("Thin");
        radioThin.setToolTipText("");
        radioThin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioThinItemStateChanged(evt);
            }
        });
        radioThin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioThinActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioThick);
        radioThick.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioThick.setText("Thick");
        radioThick.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioThickItemStateChanged(evt);
            }
        });
        radioThick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioThickActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioCheese);
        radioCheese.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioCheese.setText("Cheese");
        radioCheese.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioCheeseItemStateChanged(evt);
            }
        });
        radioCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCheeseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(radioThin)
                        .addGap(60, 60, 60)
                        .addComponent(radioThick)
                        .addGap(62, 62, 62)
                        .addComponent(radioCheese))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Crust)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Crust, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioThin)
                    .addComponent(radioThick)
                    .addComponent(radioCheese))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Styles.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        Styles.setText("Select Style:");

        buttonGroup2.add(radioNewYork);
        radioNewYork.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioNewYork.setText("New York Style");
        radioNewYork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNewYorkActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioChicago);
        radioChicago.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioChicago.setText("Chicago");
        radioChicago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChicagoActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioSicilian);
        radioSicilian.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioSicilian.setText("Sicilian");
        radioSicilian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSicilianActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioVeggie);
        radioVeggie.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioVeggie.setText("Veggie");
        radioVeggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVeggieActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioEverything);
        radioEverything.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioEverything.setText("Everything");
        radioEverything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEverythingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNewYork)
                    .addComponent(Styles)
                    .addComponent(radioChicago)
                    .addComponent(radioSicilian)
                    .addComponent(radioVeggie)
                    .addComponent(radioEverything))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Styles)
                .addGap(18, 18, 18)
                .addComponent(radioNewYork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioChicago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioSicilian)
                .addGap(12, 12, 12)
                .addComponent(radioVeggie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioEverything)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));

        Title.setFont(new java.awt.Font("Kokonor", 1, 36)); // NOI18N
        Title.setText("Pizza Palace");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(toppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toppingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioThinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioThinActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_radioThinActionPerformed

    private void checkPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPepperoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPepperoniActionPerformed

    private void checkOnionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOnionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOnionsActionPerformed

    private void checkPineapppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPineapppleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPineapppleActionPerformed

    private void totalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalBoxActionPerformed

    private void checkMushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMushroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMushroomActionPerformed

    private void checkMeatballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMeatballActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMeatballActionPerformed

    private void radioThickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioThickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioThickActionPerformed

    private void radioCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCheeseActionPerformed

    private void radioThinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioThinItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 17);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 17);
        }
    }//GEN-LAST:event_radioThinItemStateChanged

    private void radioThickItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioThickItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 19.30);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 19.30);
        }
    }//GEN-LAST:event_radioThickItemStateChanged

    private void radioCheeseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioCheeseItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 20.15);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 20.15);
        }
    }//GEN-LAST:event_radioCheeseItemStateChanged

    private void radioNewYorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNewYorkActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        radioCheese.setSelected(true);
        checkPepperoni.setSelected(true);     
    }//GEN-LAST:event_radioNewYorkActionPerformed

    private void radioChicagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChicagoActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        radioThick.setSelected(true);
        checkMeatball.setSelected(true);
        checkMushroom.setSelected(true);
    }//GEN-LAST:event_radioChicagoActionPerformed

    private void checkPepperoniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPepperoniItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 2);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 2);
        }
    }//GEN-LAST:event_checkPepperoniItemStateChanged

    private void checkPineapppleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPineapppleItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 2.4);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 2.4);
        }
    }//GEN-LAST:event_checkPineapppleItemStateChanged

    private void checkMushroomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkMushroomItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 3.4);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 3.4);
        }
    }//GEN-LAST:event_checkMushroomItemStateChanged

    private void checkMeatballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkMeatballItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 2.1);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 2.1);
        }
    }//GEN-LAST:event_checkMeatballItemStateChanged

    private void checkChickenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkChickenItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 3.25);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 3.25);
        }
    }//GEN-LAST:event_checkChickenItemStateChanged

    private void checkOnionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkOnionsItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) + 1.8);    
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            totalBox.setValue((double)(totalBox.getValue()) - 1.8);
        }
    }//GEN-LAST:event_checkOnionsItemStateChanged

    private void radioSicilianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSicilianActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        radioThin.setSelected(true);
        checkMeatball.setSelected(true);
        checkOnions.setSelected(true);
        checkPepperoni.setSelected(true);
    }//GEN-LAST:event_radioSicilianActionPerformed

    private void radioVeggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVeggieActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        radioThin.setSelected(true);
        checkMushroom.setSelected(true);
        checkOnions.setSelected(true);
    }//GEN-LAST:event_radioVeggieActionPerformed

    private void radioEverythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEverythingActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        radioCheese.setSelected(true);
        checkChicken.setSelected(true);
        checkPineappple.setSelected(true);
        checkMushroom.setSelected(true);
        checkOnions.setSelected(true);
        checkPepperoni.setSelected(true);
        checkMeatball.setSelected(true);
    }//GEN-LAST:event_radioEverythingActionPerformed

    private void orderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbuttonActionPerformed
        // TODO add your handling code here:
        if (isCrustEmpty()) {
            showMessageDialog(null, "Please select at least one crust");
        } else if ((int)quantitySpinner.getValue() == 0) {
            showMessageDialog(null, "Quantity can't be 0");    
        } else {
            showMessageDialog(null, "Your Order is Complete. Thank you"); 
            clearCheckboxes();
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
            quantitySpinner.setValue((int)1);
            tipBox.setValue((int)0);
            tipCombobox.setSelectedIndex(0);
            
        }
        
    }//GEN-LAST:event_orderbuttonActionPerformed

    private void tipComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipComboboxActionPerformed
        // TODO add your handling code here:
        double onePizzaTotal = oneTotal();
        if (tipCombobox.getSelectedIndex() == 1) {
            tipBox.setValue((double)(0.15 * (double)totalBox.getValue()));
        } else if (tipCombobox.getSelectedIndex() == 2) {
            tipBox.setValue((double)(0.2 * (double)totalBox.getValue()));
        } else if (tipCombobox.getSelectedIndex() == 3) {
            tipBox.setValue((double)(0.3 * (double)totalBox.getValue()));
        } else if (tipCombobox.getSelectedIndex() == 4) {
            tipBox.setValue((double)(0.4 * (double)totalBox.getValue()));
        } else {
            tipBox.setValue((double)0);
        }
        totalBox.setValue(onePizzaTotal * ((int)quantitySpinner.getValue()) + (double)tipBox.getValue());
    }//GEN-LAST:event_tipComboboxActionPerformed

    private void tipBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipBoxActionPerformed

    private void tipBoxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tipBoxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tipBoxInputMethodTextChanged

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        double onePizzaTotal = oneTotal();
        double tip = (double)tipBox.getValue();
        if (tip < 0) {
            showMessageDialog(null, "Tip can't be less than 0"); 
        } else if ((int)quantitySpinner.getValue() == 0) {
            showMessageDialog(null, "Quantity can't be 0");
        }
        else {
            totalBox.setValue(onePizzaTotal * ((int)quantitySpinner.getValue()) + tip);    
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void quantitySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantitySpinnerStateChanged
        // TODO add your handling code here
        double onePizzaTotal = oneTotal();
        totalBox.setValue(onePizzaTotal * ((int)quantitySpinner.getValue()) + (double)tipBox.getValue());
    }//GEN-LAST:event_quantitySpinnerStateChanged

    private void totalBoxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_totalBoxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBoxInputMethodTextChanged

    private void totalBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBoxPropertyChange

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        clearCheckboxes();
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        quantitySpinner.setValue((int)1);
        tipBox.setValue((int)0);
        tipCombobox.setSelectedIndex(0);
        
    }//GEN-LAST:event_cancelbuttonActionPerformed
    
    
    private double oneTotal() {
        double total = 0;
        if (radioThin.isSelected()) {
            total += 17;
        } else if (radioThick.isSelected()) {
            total += 19.30;
        } else if (radioCheese.isSelected()) {
            total += 20.15;
        }
        
        if (checkPepperoni.isSelected()) {
            total += 2;
        }
        
        if (checkPineappple.isSelected()) {
            total += 2.4;
        }
        if (checkMushroom.isSelected()) {
            total += 3.4;
        }
        if (checkMeatball.isSelected()) {
            total += 2.10;
        }
        if (checkChicken.isSelected()) {
            total += 3.25;
        }
        if (checkOnions.isSelected()) {
            total += 1.8;
        }
        
        return total;
        
    }
    
    
    private boolean isCrustEmpty() {
        if (radioThin.isSelected() == false & radioThick.isSelected()== false & radioCheese.isSelected() == false) {
            return true;
        } else {
            return false;
        }
    }
    
    private void clearCheckboxes() {
        checkPepperoni.setSelected(false);
        checkPineappple.setSelected(false);
        checkMushroom.setSelected(false);
        checkMeatball.setSelected(false);
        checkChicken.setSelected(false);
        checkOnions.setSelected(false);
    }
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaShopApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaShopApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaShopApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaShopApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaShopApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Checkout;
    private javax.swing.JLabel Crust;
    private javax.swing.JLabel Styles;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Toppings;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JCheckBox checkChicken;
    private javax.swing.JCheckBox checkMeatball;
    private javax.swing.JCheckBox checkMushroom;
    private javax.swing.JCheckBox checkOnions;
    private javax.swing.JCheckBox checkPepperoni;
    private javax.swing.JCheckBox checkPineappple;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton orderbutton;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JRadioButton radioCheese;
    private javax.swing.JRadioButton radioChicago;
    private javax.swing.JRadioButton radioEverything;
    private javax.swing.JRadioButton radioNewYork;
    private javax.swing.JRadioButton radioSicilian;
    private javax.swing.JRadioButton radioThick;
    private javax.swing.JRadioButton radioThin;
    private javax.swing.JRadioButton radioVeggie;
    private javax.swing.JLabel tip;
    private javax.swing.JFormattedTextField tipBox;
    private javax.swing.JComboBox<String> tipCombobox;
    private javax.swing.JPanel toppingPanel;
    private javax.swing.JLabel total;
    private javax.swing.JFormattedTextField totalBox;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
